### PR TITLE
150 improve unit test coverage for mapless mongo core

### PR DESCRIPTION
**Pull request by sebastianconcept**
- Renamed project packages 
- Added some unit tests
- Removed a deprecated unused class
- Adjusted some delays in time sensitive tests (for example the ones that depend on Redis PUBSUB)

### CODE REVIEW

**Comment by sebastianconcept** [comment]
Is okay for you @paulwilke like this ? https://app.codecov.io/gh/sebastianconcept/Mapless/pull/160

We can do more in a next round

**Review by giolvani — APPROVED** [review]
LGTM

**Review by nicwease — APPROVED** [review]

**Review by paulwilke — APPROVED** [review]
Great!

**Review by fgarau — COMMENTED** [review]
all good so far -- mostly category renaming, class renaming and changes to sunits

**Pull request merged**
